=== jvelarde94/jeremyvelarde/nyctourism/z-final(old)/midterm documents/public1.xsd
<?xml version="1.0" encoding="UTF-8"  standalone="yes" ?>
<!--
XML MIDTERM
   Schema for public.xml
   Author: Jeremy Velarde
   Date:   10/20/2016
   File: public1.xsd (SPECIFICALLY TO BE USED AGAINST public.xml)
   REQ. 5
-->      

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:attribute name="type" type="trainType" />
	<xs:attribute name="direction" type="directionType" />
	<xs:element name="method" type="xs:string" />
	<xs:element name="location" type="xs:string" />
	<xs:element name="destination" type="xs:string" />
	<xs:element name="trainFrom" type="xs:string" />
	<xs:element name="trainTo" type="xs:string" />
	<xs:element name="direction" type="xs:string" />
 
	<xs:simpleType name="trainType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="peak"/>
			<xs:enumeration value="offpeak"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="directionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="east"/>
			<xs:enumeration value="west"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="transportations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="transportation" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="transportation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transport" />
				<xs:element ref="location" />
				<xs:element ref="destination" />
				<xs:element ref="train" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="subway" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="transport">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="method" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
				
	<xs:element name="train">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="trainFrom" />
				<xs:element ref="trainTo" />
			</xs:sequence>
			<xs:attribute ref="type" />
			<xs:attribute ref="direction" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="subway">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="direction" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== jvelarde94/jeremyvelarde/nyctourism/midterm documents/public.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!--
XML MIDTERM
   Transportation in NYC
   Author: Jeremy Velarde
   Date:   10/20/2016
   File: public.xml (SPECIFICALLY TO BE USED AGAINST public1.xsd)
   REQ. 3
-->      
<!DOCTYPE transportations SYSTEM "public.dtd"> <!-- REQ. 4 -->

<transportations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	  xsi:noNamespaceSchemaLocation="public1.xsd">
	  <!-- REQ. 6 -->
	  <!--no namespace, as this was created prior to publicprivate.xml-->
	  
	<transportation>
		<transport>
			<method>Train</method>
		</transport>
		<location>Queens</location>
		<destination>Manhattan</destination>
		<train type="peak" direction="west">
			<trainFrom>Jamaica</trainFrom>
			<trainTo>Penn Station</trainTo>
		</train>
	</transportation>
	
	<transportation>
		<transport>
			<method>Subway</method>
		</transport>
		<location>Penn Station</location>
		<destination>Times Square</destination>
		<subway>
				<direction>Uptown: 34th - 42nd</direction>
		</subway>
	</transportation>
		
	<transportation>
		<transport>
			<method>Subway</method>
		</transport>
		<location>Times Square</location>
		<destination>Empire State Building</destination>
		<subway>
				<direction>Downtown: 49th - 34th</direction>
		</subway>
	</transportation>	
	
	<transportation>	
		<transport>
			<method>Train</method>
		</transport>
		<location>Manhattan</location>
		<destination>Queens</destination>
		<train type="offpeak" direction="east">
			<trainFrom>Penn Station</trainFrom>
			<trainTo>Jamaica</trainTo>
		</train>
	</transportation>
	
</transportations>
